name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main  # Ganti kalau branch utama kamu beda

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.if0_39668451 }}
          password: ${{ secrets.1Sln68EYt0a7n0 }}
          server-dir: /htdocs/
